# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/Room')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('Norating', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('starrating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=100)),
                ('place', models.CharField(default='maldives', max_length=100)),
            ],
        ),
    ]
